### ISSUE TITLE
ODR violation

### ISSUE THREAD

**Issue by arthaud** [yuri-kilochek/boost.scope_guard#6]
Using `__COUNTER__` for generated names could lead to ODR (One Definition Rule) violations. This has been mentioned in Alexandrescu's talk, see https://www.youtube.com/watch?v=WjTrfoiB0MQ&t=1h4m

Basically, if you use `BOOST_SCOPE_GUARD` in a header file, the generated variable name can be different across compilation unit.

It probably works, but it still is ill-formed C++. I think it's worth mentioning it in the limitations.

**Comment by yuri-kilochek** [comment]
Ouch. Yeah, that's too dangerous. I think `__COUNTER__` has to go.

**Comment by yuri-kilochek** [comment]
Resolved by 7c0d552bd87889092c2405b3a417c1e543300f72.
